name: Max Rydahl Andersen
title: "@maxandersen"
org: Organization
base_url: ''
twitter_url: https://twiter.com/maxandersen
facebook_url: https://www.facebook.com/maxandersen
github_url: http://github.com/maxandersen
googleplus_url: https://plus.google.com/+maxrydahlandersen

disqus: blogxamdk

asciidoctor:
  :safe: safe
  :attributes:
    imagesdir: ./@
    icons: font
    idprefix: ''
    idseparator: '-'
    sectanchors: ''
    linkattrs: ''
    source-highlighter: prettify

profiles:
  development:
    base_url: http://localhost:4242
    disqus_developer: true

  production:
    base_url: http://xam.dk
    